version: '3'

services:
  soundweb-control:
    hostname: soundweb-control
    image: quphoria/soundweb-control
    volumes:
      - ./data:/data
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    restart: unless-stopped

  hiqnet-websocket-proxy:
    hostname: hiqnet-websocket-proxy
    image: quphoria/hiqnet-websocket-proxy
    ports:
      - "3804:3804/udp"
      - "3804:3804/tcp"
    volumes:
      - ./data/backend:/app/config
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    restart: unless-stopped

  nginx-proxy:
    image: nginx
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../ssl/cert.crt:/etc/ssl/cert.crt:ro
      - ../ssl/cert.key:/etc/ssl/cert.key:ro
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    restart: unless-stopped

networks:
  backend:
